# Generated by Django 5.1.7 on 2025-03-24 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, help_text="Enter the contact's address (optional, max 500 characters)", max_length=500, validators=[django.core.validators.MaxLengthValidator(500, message='Address cannot exceed 500 characters.')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='Enter a valid email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text="Enter the contact's full name (2-100 characters)", max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='Name must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(100, message='Name cannot exceed 100 characters.')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, help_text='Enter any additional notes (optional, max 1000 characters)', max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000, message='Notes cannot exceed 1000 characters.')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(help_text='Enter a valid phone number (9-15 digits, optionally starting with +)', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
